/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SpotBase } from "./SpotBase";
export * as factories from "./factories";
export { SpotBase__factory } from "./factories/SpotBase__factory";
